services:
  - type: worker
    name: herald-of-the-grove
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: TIMEZONE
        sync: false
